/* ============================================================
 * Sample PR data — a realistic WorkOS SSO change.
 * #1847 — "Support OIDC discovery for Microsoft Entra ID"
 *
 * The diffs are real-looking TypeScript (not compiled — these are
 * cosmetic snippets crafted to read well in the prototype).
 *
 * Each "chapter" is a semantic beat. AI narration sits between
 * chapters and between hunks. Hunks reference files & line ranges.
 * ============================================================ */

const PR = {
  number: 1847,
  repo: "workos/workos",
  title: "Support OIDC discovery for Microsoft Entra ID",
  branch: "fb/entra-oidc-discovery",
  base: "main",
  state: "open",
  status: "draft", // draft | open | merged
  author: {
    handle: "fbarber",
    name: "Frances Barber",
    avatar: "FB",
    color: "#6565EC",
  },
  reviewers: [
    { handle: "ynguyen", name: "Yusuf Nguyen", avatar: "YN", color: "#208368", state: "reviewing" },
    { handle: "achen", name: "Adaeze Chen", avatar: "AC", color: "#CA244D", state: "approved" },
  ],
  createdAt: "2 days ago",
  updatedAt: "14 minutes ago",
  description:
    "Microsoft Entra ID (formerly Azure AD) recently shipped well-known OIDC discovery on tenant-scoped issuer URLs. We were still asking customers to paste the Authorization, Token, and JWKS URLs by hand. This PR teaches the SSO connection setup to discover them from the issuer.",
  stats: {
    files: 7,
    additions: 184,
    deletions: 47,
    commits: 9,
  },
  checks: {
    passing: 11,
    failing: 0,
    pending: 1,
  },
  // ----------------------------------------------------------
  // Chapters — the spine of the story
  // ----------------------------------------------------------
  chapters: [
    {
      id: "ch1",
      title: "Teach the connection model what 'discovery' is",
      summary:
        "Before any UI or network code, we extend the SSO connection schema with a new `discovery_mode` field. This is the foundation everything else hangs off of — it lets the rest of the codebase ask a connection 'do we have the metadata, or do we need to fetch it?' without re-parsing URLs every time.",
      risk: "low",
      reviewed: true,
      hunks: [
        {
          id: "h-conn-type",
          file: "packages/sso/src/connections/connection.model.ts",
          range: "L42–L67",
          before: 42,
          // Each line: { kind: ' '|'+'|'-', n: number|null, m: number|null, code }
          lines: [
            { kind: " ", n: 42, m: 42, code: "export type SsoConnectionType =" },
            { kind: " ", n: 43, m: 43, code: "  | 'OktaSAML'" },
            { kind: " ", n: 44, m: 44, code: "  | 'GoogleSAML'" },
            { kind: " ", n: 45, m: 45, code: "  | 'GenericOIDC'" },
            { kind: "-", n: 46, m: null, code: "  | 'MicrosoftOIDC';" },
            { kind: "+", n: null, m: 46, code: "  | 'MicrosoftOIDC'" },
            { kind: "+", n: null, m: 47, code: "  | 'EntraOIDC';" },
            { kind: " ", n: 47, m: 48, code: "" },
            { kind: " ", n: 48, m: 49, code: "export interface SsoConnection {" },
            { kind: " ", n: 49, m: 50, code: "  id: string;" },
            { kind: " ", n: 50, m: 51, code: "  type: SsoConnectionType;" },
            { kind: " ", n: 51, m: 52, code: "  organizationId: string;" },
            { kind: " ", n: 52, m: 53, code: "  state: 'draft' | 'active' | 'inactive';" },
            { kind: "+", n: null, m: 54, code: "" },
            { kind: "+", n: null, m: 55, code: "  /**" },
            { kind: "+", n: null, m: 56, code: "   * How endpoint metadata was obtained." },
            { kind: "+", n: null, m: 57, code: "   *  - 'manual'    customer pasted endpoints" },
            { kind: "+", n: null, m: 58, code: "   *  - 'discovery' fetched from the issuer's well-known doc" },
            { kind: "+", n: null, m: 59, code: "   */" },
            { kind: "+", n: null, m: 60, code: "  discoveryMode: 'manual' | 'discovery';" },
            { kind: "+", n: null, m: 61, code: "  discoveredAt?: Date;" },
            { kind: " ", n: 53, m: 62, code: "  oidc?: OidcConfig;" },
            { kind: " ", n: 54, m: 63, code: "  saml?: SamlConfig;" },
            { kind: " ", n: 55, m: 64, code: "}" },
          ],
          comments: [],
        },
        {
          id: "h-oidc-config",
          file: "packages/sso/src/connections/connection.model.ts",
          range: "L120–L141",
          before: 120,
          lines: [
            { kind: " ", n: 120, m: 129, code: "export interface OidcConfig {" },
            { kind: " ", n: 121, m: 130, code: "  clientId: string;" },
            { kind: " ", n: 122, m: 131, code: "  clientSecret: string;" },
            { kind: "-", n: 123, m: null, code: "  authorizationUrl: string;" },
            { kind: "-", n: 124, m: null, code: "  tokenUrl: string;" },
            { kind: "-", n: 125, m: null, code: "  jwksUrl: string;" },
            { kind: "-", n: 126, m: null, code: "  issuer: string;" },
            { kind: "+", n: null, m: 132, code: "  issuer: string;" },
            { kind: "+", n: null, m: 133, code: "  authorizationUrl?: string;" },
            { kind: "+", n: null, m: 134, code: "  tokenUrl?: string;" },
            { kind: "+", n: null, m: 135, code: "  jwksUrl?: string;" },
            { kind: " ", n: 127, m: 136, code: "  scopes: string[];" },
            { kind: " ", n: 128, m: 137, code: "}" },
          ],
          comments: [
            {
              id: "c1",
              author: "ynguyen",
              line: 134,
              side: "after",
              body: "Making these optional is the right call — but I'm a little nervous about runtime safety.\n\nCould we add a narrow invariant somewhere downstream? Otherwise we'll get cryptic null errors deep in the redirect handler.\n\n```ts\nfunction assertResolved(c: ConnectionConfig): asserts c is ResolvedConfig {\n  if (!c.authorizationUrl || !c.tokenUrl || !c.jwksUrl) {\n    throw new ConfigError('connection_not_resolved', { id: c.id });\n  }\n}\n```\n\ncc @fbarber — wonder if this should live on the model itself, similar to what we did in workos/workos#1402.",
              createdAt: "1 hour ago",
              syncStatus: "synced",
              source: "diffapp",
              replies: [
                {
                  id: "c1r1",
                  author: "fbarber",
                  body: "> wonder if it should live on the model itself though\n\nGood call. There's an `assertResolved()` in the next chapter — but you're right, putting it on the model itself is cleaner. Let me push a follow-up:\n\n- [x] Sketch the invariant signature\n- [x] Move into `ConnectionConfig` class\n- [ ] Add unit tests for the unresolved case\n- [ ] Update `redirect-handler.ts` to drop its local check\n\nWill ping when ready.",
                  createdAt: "47 minutes ago",
                  syncStatus: "synced",
                  source: "github",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "ch2",
      title: "Fetch the well-known document",
      summary:
        "Now we actually go get it. A small, focused fetcher that takes an issuer URL, normalizes it, hits `/.well-known/openid-configuration`, and validates the response shape. We deliberately don't cache here — that's the next chapter's job — so this stays trivially testable.",
      risk: "medium",
      reviewed: false,
      hunks: [
        {
          id: "h-discovery",
          file: "packages/sso/src/oidc/discovery.ts",
          range: "new file",
          isNewFile: true,
          before: 1,
          lines: [
            { kind: "+", n: null, m: 1, code: "import { z } from 'zod';" },
            { kind: "+", n: null, m: 2, code: "import { fetch } from '../http';" },
            { kind: "+", n: null, m: 3, code: "import { DiscoveryError } from '../errors';" },
            { kind: "+", n: null, m: 4, code: "" },
            { kind: "+", n: null, m: 5, code: "const DiscoveryDoc = z.object({" },
            { kind: "+", n: null, m: 6, code: "  issuer: z.string().url()," },
            { kind: "+", n: null, m: 7, code: "  authorization_endpoint: z.string().url()," },
            { kind: "+", n: null, m: 8, code: "  token_endpoint: z.string().url()," },
            { kind: "+", n: null, m: 9, code: "  jwks_uri: z.string().url()," },
            { kind: "+", n: null, m: 10, code: "  response_types_supported: z.array(z.string())," },
            { kind: "+", n: null, m: 11, code: "  scopes_supported: z.array(z.string()).optional()," },
            { kind: "+", n: null, m: 12, code: "});" },
            { kind: "+", n: null, m: 13, code: "" },
            { kind: "+", n: null, m: 14, code: "export type DiscoveryDoc = z.infer<typeof DiscoveryDoc>;" },
            { kind: "+", n: null, m: 15, code: "" },
            { kind: "+", n: null, m: 16, code: "export async function discover(issuer: string): Promise<DiscoveryDoc> {" },
            { kind: "+", n: null, m: 17, code: "  const url = normalizeIssuer(issuer) + '/.well-known/openid-configuration';" },
            { kind: "+", n: null, m: 18, code: "  const res = await fetch(url, { timeoutMs: 5_000 });" },
            { kind: "+", n: null, m: 19, code: "  if (!res.ok) {" },
            { kind: "+", n: null, m: 20, code: "    throw new DiscoveryError('issuer_unreachable', { url, status: res.status });" },
            { kind: "+", n: null, m: 21, code: "  }" },
            { kind: "+", n: null, m: 22, code: "  const json = await res.json();" },
            { kind: "+", n: null, m: 23, code: "  const parsed = DiscoveryDoc.safeParse(json);" },
            { kind: "+", n: null, m: 24, code: "  if (!parsed.success) {" },
            { kind: "+", n: null, m: 25, code: "    throw new DiscoveryError('malformed_document', { issues: parsed.error.issues });" },
            { kind: "+", n: null, m: 26, code: "  }" },
            { kind: "+", n: null, m: 27, code: "  return parsed.data;" },
            { kind: "+", n: null, m: 28, code: "}" },
            { kind: "+", n: null, m: 29, code: "" },
            { kind: "+", n: null, m: 30, code: "function normalizeIssuer(input: string): string {" },
            { kind: "+", n: null, m: 31, code: "  return input.replace(/\\/$/, '');" },
            { kind: "+", n: null, m: 32, code: "}" },
          ],
          comments: [
            {
              id: "c2",
              author: "achen",
              line: 18,
              side: "after",
              body: "5s timeout feels short for the first request. Entra cold-starts can be **~3s** based on what we saw in #1402.\n\n```suggestion\n  const res = await fetch(url, { timeoutMs: 10_000 });\n```\n\nWe can tighten if telemetry shows we never need it.",
              createdAt: "3 hours ago",
              syncStatus: "synced",
              source: "github",
              replies: [],
            },
            {
              id: "c2-bot1",
              author: "coderabbit[bot]",
              line: 17,
              side: "after",
              body: "**Consider extracting the timeout constant.** Magic numbers like `5_000` are easier to tune when named.\n\n```suggestion\nconst DISCOVERY_TIMEOUT_MS = 5_000;\n\nexport async function discover(issuer: string): Promise<DiscoveryDoc> {\n  const url = normalizeIssuer(issuer) + '/.well-known/openid-configuration';\n  const res = await fetch(url, { timeoutMs: DISCOVERY_TIMEOUT_MS });\n```",
              createdAt: "3 hours ago",
              syncStatus: "synced",
              source: "github",
              replies: [],
            },
            {
              id: "c2-bot2",
              author: "greptile[bot]",
              line: 22,
              side: "after",
              body: "`response.ok` covers 2xx but the well-known doc spec mandates 200 specifically. Recommend `response.status === 200`.",
              createdAt: "3 hours ago",
              syncStatus: "synced",
              source: "github",
              replies: [],
            },
            {
              id: "c2-bot3",
              author: "claude-review[bot]",
              line: 25,
              side: "after",
              body: "**Schema validation is good** but `safeParse` would let you surface a structured `DiscoveryError('malformed_document')` instead of throwing the raw Zod issue.\n\nWorth aligning with how we treat connection-config errors in `packages/sso/src/errors.ts`:\n\n1. Use `safeParse` and inspect `parsed.success`\n2. Map `parsed.error.issues` into a single `DiscoveryError`\n3. Keep the original Zod issues on `cause` for telemetry\n\nSee https://docs.workos.com/reference/errors/discovery for the full error contract.",
              createdAt: "2 hours ago",
              syncStatus: "synced",
              source: "github",
              replies: [],
            },
          ],
        },
        {
          id: "h-errors",
          file: "packages/sso/src/errors.ts",
          range: "L88–L102",
          before: 88,
          lines: [
            { kind: " ", n: 88, m: 88, code: "export class SsoError extends WorkosError {" },
            { kind: " ", n: 89, m: 89, code: "  constructor(public code: string, public meta?: Record<string, unknown>) {" },
            { kind: " ", n: 90, m: 90, code: "    super(`sso.${code}`);" },
            { kind: " ", n: 91, m: 91, code: "  }" },
            { kind: " ", n: 92, m: 92, code: "}" },
            { kind: "+", n: null, m: 93, code: "" },
            { kind: "+", n: null, m: 94, code: "export class DiscoveryError extends SsoError {" },
            { kind: "+", n: null, m: 95, code: "  constructor(" },
            { kind: "+", n: null, m: 96, code: "    code: 'issuer_unreachable' | 'malformed_document' | 'tls_failure'," },
            { kind: "+", n: null, m: 97, code: "    meta?: Record<string, unknown>," },
            { kind: "+", n: null, m: 98, code: "  ) {" },
            { kind: "+", n: null, m: 99, code: "    super(`discovery.${code}`, meta);" },
            { kind: "+", n: null, m: 100, code: "  }" },
            { kind: "+", n: null, m: 101, code: "}" },
          ],
          comments: [],
        },
      ],
    },
    {
      id: "ch3",
      title: "Cache the discovery doc with a TTL",
      summary:
        "Discovery documents are stable but not immutable — Microsoft has rotated signing keys mid-quarter before. We cache by issuer URL with a 1-hour TTL, with a stale-while-revalidate fallback so an outage at the issuer doesn't break logins.",
      risk: "medium",
      reviewed: false,
      hunks: [
        {
          id: "h-discovery-cache",
          file: "packages/sso/src/oidc/discovery-cache.ts",
          range: "new file",
          isNewFile: true,
          before: 1,
          lines: [
            { kind: "+", n: null, m: 1, code: "import { LRUCache } from 'lru-cache';" },
            { kind: "+", n: null, m: 2, code: "import { discover, DiscoveryDoc } from './discovery';" },
            { kind: "+", n: null, m: 3, code: "" },
            { kind: "+", n: null, m: 4, code: "const FRESH_TTL_MS = 60 * 60 * 1_000;     // 1 hour" },
            { kind: "+", n: null, m: 5, code: "const STALE_TTL_MS = 24 * 60 * 60 * 1_000; // 24 hours" },
            { kind: "+", n: null, m: 6, code: "" },
            { kind: "+", n: null, m: 7, code: "type CacheEntry = { doc: DiscoveryDoc; fetchedAt: number };" },
            { kind: "+", n: null, m: 8, code: "" },
            { kind: "+", n: null, m: 9, code: "const cache = new LRUCache<string, CacheEntry>({" },
            { kind: "+", n: null, m: 10, code: "  max: 5_000," },
            { kind: "+", n: null, m: 11, code: "  ttl: STALE_TTL_MS," },
            { kind: "+", n: null, m: 12, code: "});" },
            { kind: "+", n: null, m: 13, code: "" },
            { kind: "+", n: null, m: 14, code: "export async function discoverCached(issuer: string): Promise<DiscoveryDoc> {" },
            { kind: "+", n: null, m: 15, code: "  const hit = cache.get(issuer);" },
            { kind: "+", n: null, m: 16, code: "  const fresh = hit && Date.now() - hit.fetchedAt < FRESH_TTL_MS;" },
            { kind: "+", n: null, m: 17, code: "  if (fresh) return hit.doc;" },
            { kind: "+", n: null, m: 18, code: "" },
            { kind: "+", n: null, m: 19, code: "  try {" },
            { kind: "+", n: null, m: 20, code: "    const doc = await discover(issuer);" },
            { kind: "+", n: null, m: 21, code: "    cache.set(issuer, { doc, fetchedAt: Date.now() });" },
            { kind: "+", n: null, m: 22, code: "    return doc;" },
            { kind: "+", n: null, m: 23, code: "  } catch (err) {" },
            { kind: "+", n: null, m: 24, code: "    if (hit) return hit.doc; // stale-while-revalidate" },
            { kind: "+", n: null, m: 25, code: "    throw err;" },
            { kind: "+", n: null, m: 26, code: "  }" },
            { kind: "+", n: null, m: 27, code: "}" },
          ],
          comments: [
            {
              id: "c3",
              author: "ynguyen",
              line: 24,
              side: "after",
              body: "Love SWR here :sparkles:\n\nOne thought: when we serve stale, should we emit a metric so SRE notices the issuer outage? Right now it's invisible.\n\n```diff\n   if (cached && now - cached.fetchedAt < TTL_MS) return cached.doc;\n   try {\n     const fresh = await discover(issuer);\n     cache.set(issuer, { doc: fresh, fetchedAt: now });\n     return fresh;\n   } catch (e) {\n+    metrics.increment('oidc.discovery.stale_serve', { issuer });\n     if (cached) return cached.doc; // SWR: serve last known\n     throw e;\n   }\n```",
              createdAt: "32 minutes ago",
              syncStatus: "syncing",
              source: "diffapp",
              replies: [],
            },
          ],
        },
      ],
    },
    {
      id: "ch4",
      title: "Wire discovery into the connection setup flow",
      summary:
        "The actual user-visible change. When an admin selects 'Microsoft Entra ID' in the Admin Portal and pastes their tenant's issuer URL, we now call `discoverCached()` and pre-populate the rest of the form. They can still override anything if they want — discovery is a starting point, not a constraint.",
      risk: "high",
      reviewed: false,
      hunks: [
        {
          id: "h-setup-form",
          file: "packages/admin-portal/src/sso/SetupFormOIDC.tsx",
          range: "L88–L142",
          before: 88,
          lines: [
            { kind: " ", n: 88, m: 88, code: "function SetupFormOIDC({ connection, onSave }: Props) {" },
            { kind: " ", n: 89, m: 89, code: "  const [draft, setDraft] = useState<OidcConfig>(connection.oidc ?? EMPTY);" },
            { kind: "+", n: null, m: 90, code: "  const [discovering, setDiscovering] = useState(false);" },
            { kind: "+", n: null, m: 91, code: "  const [discoveryError, setDiscoveryError] = useState<string | null>(null);" },
            { kind: " ", n: 90, m: 92, code: "" },
            { kind: "+", n: null, m: 93, code: "  async function handleIssuerBlur(issuer: string) {" },
            { kind: "+", n: null, m: 94, code: "    if (!isLikelyIssuerUrl(issuer)) return;" },
            { kind: "+", n: null, m: 95, code: "    setDiscovering(true);" },
            { kind: "+", n: null, m: 96, code: "    setDiscoveryError(null);" },
            { kind: "+", n: null, m: 97, code: "    try {" },
            { kind: "+", n: null, m: 98, code: "      const doc = await api.sso.discover({ issuer });" },
            { kind: "+", n: null, m: 99, code: "      setDraft((d) => ({" },
            { kind: "+", n: null, m: 100, code: "        ...d," },
            { kind: "+", n: null, m: 101, code: "        issuer: doc.issuer," },
            { kind: "+", n: null, m: 102, code: "        authorizationUrl: doc.authorization_endpoint," },
            { kind: "+", n: null, m: 103, code: "        tokenUrl: doc.token_endpoint," },
            { kind: "+", n: null, m: 104, code: "        jwksUrl: doc.jwks_uri," },
            { kind: "+", n: null, m: 105, code: "      }));" },
            { kind: "+", n: null, m: 106, code: "    } catch (err) {" },
            { kind: "+", n: null, m: 107, code: "      setDiscoveryError(humanizeDiscoveryError(err));" },
            { kind: "+", n: null, m: 108, code: "    } finally {" },
            { kind: "+", n: null, m: 109, code: "      setDiscovering(false);" },
            { kind: "+", n: null, m: 110, code: "    }" },
            { kind: "+", n: null, m: 111, code: "  }" },
            { kind: "+", n: null, m: 112, code: "" },
            { kind: " ", n: 91, m: 113, code: "  return (" },
            { kind: " ", n: 92, m: 114, code: "    <Form onSubmit={() => onSave(draft)}>" },
            { kind: " ", n: 93, m: 115, code: "      <Field label=\"Issuer URL\" hint=\"e.g. https://login.microsoftonline.com/{tenant}/v2.0\">" },
            { kind: "-", n: 94, m: null, code: "        <TextField value={draft.issuer} onChange={(v) => setDraft({ ...draft, issuer: v })} />" },
            { kind: "+", n: null, m: 116, code: "        <TextField" },
            { kind: "+", n: null, m: 117, code: "          value={draft.issuer}" },
            { kind: "+", n: null, m: 118, code: "          onChange={(v) => setDraft({ ...draft, issuer: v })}" },
            { kind: "+", n: null, m: 119, code: "          onBlur={(e) => handleIssuerBlur(e.target.value)}" },
            { kind: "+", n: null, m: 120, code: "          trailing={discovering && <Spinner size=\"1\" />}" },
            { kind: "+", n: null, m: 121, code: "        />" },
            { kind: "+", n: null, m: 122, code: "        {discoveryError && <FieldError>{discoveryError}</FieldError>}" },
            { kind: " ", n: 95, m: 123, code: "      </Field>" },
            { kind: " ", n: 96, m: 124, code: "      {/* … remaining fields … */}" },
            { kind: " ", n: 97, m: 125, code: "    </Form>" },
            { kind: " ", n: 98, m: 126, code: "  );" },
            { kind: " ", n: 99, m: 127, code: "}" },
          ],
          comments: [
            {
              id: "c4",
              author: "achen",
              line: 119,
              side: "after",
              body: "Discovery on blur is nice but it'll fire if the user tabs away mid-typing. Could we debounce or only fire when the URL **actually parses cleanly**?\n\nReproduction:\n\n1. Focus the issuer field\n2. Type `https://login.micros` (incomplete)\n3. Tab away\n4. → fires a doomed discovery request\n\nNot a regression but worth tightening before launch.",
              createdAt: "3 hours ago",
              syncStatus: "synced",
              source: "github",
              replies: [
                {
                  id: "c4r1",
                  author: "fbarber",
                  body: "`isLikelyIssuerUrl` does a quick parse + scheme check, so we won't fire on partial input. But agreed re: debounce, will add a 300ms one.",
                  createdAt: "2 hours ago",
                  syncStatus: "synced",
                  source: "diffapp",
                },
                {
                  id: "c4r2",
                  author: "achen",
                  body: "Perfect, that works.",
                  createdAt: "2 hours ago",
                  syncStatus: "synced",
                  source: "github",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "ch5",
      title: "Tests & telemetry",
      summary:
        "Three new test files exercising the happy path, malformed responses, and the stale-while-revalidate branch. We also wire a `sso.discovery.duration_ms` histogram so we can see in production whether the 5s timeout is the right call.",
      risk: "low",
      reviewed: false,
      // Reshown hunks: ch5 echoes the discovery + cache code as evidence the tests cover them.
      reshow: [
        {
          ref: "h-discovery",
          framing: "<b>The fetcher under test.</b> The happy-path test below mocks <code>fetch</code> at the URL <code>discover()</code> constructs and asserts the parsed shape — the same code we wrote in chapter 2.",
          highlight: { from: 17, to: 22 },
        },
      ],
      hunks: [
        {
          id: "h-tests",
          file: "packages/sso/src/oidc/__tests__/discovery.test.ts",
          range: "new file",
          isNewFile: true,
          before: 1,
          lines: [
            { kind: "+", n: null, m: 1, code: "import { describe, it, expect } from 'vitest';" },
            { kind: "+", n: null, m: 2, code: "import { discover } from '../discovery';" },
            { kind: "+", n: null, m: 3, code: "import { mockHttp } from '../../testing/http';" },
            { kind: "+", n: null, m: 4, code: "" },
            { kind: "+", n: null, m: 5, code: "describe('discover()', () => {" },
            { kind: "+", n: null, m: 6, code: "  it('fetches and parses a well-known doc', async () => {" },
            { kind: "+", n: null, m: 7, code: "    mockHttp.get('https://issuer.example/.well-known/openid-configuration', {" },
            { kind: "+", n: null, m: 8, code: "      issuer: 'https://issuer.example'," },
            { kind: "+", n: null, m: 9, code: "      authorization_endpoint: 'https://issuer.example/authorize'," },
            { kind: "+", n: null, m: 10, code: "      token_endpoint: 'https://issuer.example/token'," },
            { kind: "+", n: null, m: 11, code: "      jwks_uri: 'https://issuer.example/jwks'," },
            { kind: "+", n: null, m: 12, code: "      response_types_supported: ['code']," },
            { kind: "+", n: null, m: 13, code: "    });" },
            { kind: "+", n: null, m: 14, code: "    const doc = await discover('https://issuer.example');" },
            { kind: "+", n: null, m: 15, code: "    expect(doc.token_endpoint).toBe('https://issuer.example/token');" },
            { kind: "+", n: null, m: 16, code: "  });" },
            { kind: "+", n: null, m: 17, code: "});" },
          ],
          comments: [],
        },
      ],
    },
  ],
};

// Build a registry of every hunk by id, plus a reverse-lookup from id → the
// chapter that owns it. Re-shown references resolve through here.
const hunkById = {};
const ownerChapterById = {};
PR.chapters.forEach((ch, idx) => {
  (ch.hunks || []).forEach(h => {
    if (h.id) {
      hunkById[h.id] = h;
      ownerChapterById[h.id] = { id: ch.id, idx, title: ch.title };
    }
  });
});

window.PR = PR;
window.hunkById = hunkById;
window.ownerChapterById = ownerChapterById;

// ---- Author registry (humans + bots) ---------------------------------------
window.AUTHORS = {
  fbarber:  { name: "Frances Barber", short: "Frances", initials: "FB", color: "#6565EC", kind: "human" },
  ynguyen:  { name: "Yusuf Nguyen",   short: "Yusuf",   initials: "YN", color: "#208368", kind: "human" },
  achen:    { name: "Adaeze Chen",    short: "Adaeze",  initials: "AC", color: "#CA244D", kind: "human" },
  "coderabbit[bot]": { name: "CodeRabbit",  short: "CodeRabbit", initials: "CR", color: "#D97706", kind: "bot" },
  "greptile[bot]":   { name: "Greptile",    short: "Greptile",   initials: "GR", color: "#0EA5E9", kind: "bot" },
  "claude-review[bot]": { name: "Claude Review", short: "Claude", initials: "CL", color: "#7C3AED", kind: "bot" },
  "github-actions[bot]": { name: "github-actions", short: "CI", initials: "CI", color: "#6E7781", kind: "bot" },
};
