import { describe, expect, it } from 'vitest';
import { renderInline } from '../Markdown';

// `renderInline` is the pure string→string core of the markdown renderer (escape + inline rules).
// The component around it needs DOMPurify + mermaid + the zustand store, none of which exist in the
// node test environment, so the inline rules are tested directly here.

describe('renderInline: italics', () => {
  it('italicizes *asterisk* emphasis', () => {
    // Regression guard for the pre-existing rule.
    expect(renderInline('*Was this helpful?*')).toBe('<em>Was this helpful?</em>');
  });

  it('italicizes _underscore_ emphasis', () => {
    // The case from workos/workos#67990 — GitHub bots sign off with `_Generated by ..._`.
    expect(renderInline('_Generated by Claude Code_')).toBe('<em>Generated by Claude Code</em>');
  });

  it('italicizes _underscore_ emphasis mid-sentence', () => {
    expect(renderInline('say _hi_ there')).toBe('say <em>hi</em> there');
  });

  it('nests _underscore_ around **bold**', () => {
    // Bold runs first; the underscore rule then wraps the <strong> in <em>.
    const out = renderInline('_**bold**_');
    expect(out).toBe('<em><strong>bold</strong></em>');
  });

  it('italicizes an underscored phrase that contains a link', () => {
    // The real PR-comment shape: `_Generated by [Claude Code](https://claude.ai/code)_`.
    // The link rule runs before the underscore rule, so the <a> ends up inside the <em>.
    const out = renderInline('_Generated by [Claude Code](https://claude.ai/code)_');
    expect(out).toContain('<em>');
    expect(out).toContain('</em>');
    expect(out).toContain('<a href="https://claude.ai/code"');
    expect(out).toContain('>Claude Code</a>');
    // The wrapping underscores themselves must be consumed, not left as literal text.
    expect(out).not.toMatch(/_<em>/);
    expect(out).not.toMatch(/<\/a>_<\/em>/);
  });

  it('leaves snake_case identifiers literal', () => {
    // GFM treats intraword underscores as text — the word-boundary anchors on both sides enforce that.
    expect(renderInline('use snake_case here')).toBe('use snake_case here');
  });

  it('leaves multi-underscore identifiers literal', () => {
    expect(renderInline('see foo_bar_baz now')).toBe('see foo_bar_baz now');
  });

  it('does not italicize when the closing underscore is followed by a word char', () => {
    // `_italic_bar` has a left-flanking opener but no right-flanking closer, so it must stay literal.
    expect(renderInline('_italic_bar')).toBe('_italic_bar');
  });

  it('leaves a trailing lone underscore literal', () => {
    expect(renderInline('done_')).toBe('done_');
  });
});
