import type { DiffFile } from '../github/types';

export type DroppedFile = {
  file: string;
  reason: 'lockfile' | 'generated' | 'snapshot' | 'vendored' | 'minified' | 'binary' | 'oversized';
  added: number;
  removed: number;
};

export type FilterResult = {
  kept: DiffFile[];
  dropped: DroppedFile[];
};

const LOCKFILE_BASENAMES = new Set([
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lock',
  'bun.lockb',
  'cargo.lock',
  'composer.lock',
  'gemfile.lock',
  'poetry.lock',
  'pdm.lock',
  'flake.lock',
  'go.sum',
  'mix.lock',
]);

const GENERATED_PATH_FRAGMENTS = ['__generated__/', '.next/', 'dist/', 'build/', '.svelte-kit/', 'coverage/'];

const SNAPSHOT_PATH_FRAGMENTS = ['__snapshots__/'];

const VENDORED_PATH_FRAGMENTS = ['vendor/', 'third_party/', 'node_modules/'];

const BINARY_EXTENSIONS = new Set([
  'png',
  'jpg',
  'jpeg',
  'gif',
  'webp',
  'avif',
  'ico',
  'pdf',
  'zip',
  'tar',
  'gz',
  'bz2',
  'xz',
  'mp3',
  'mp4',
  'mov',
  'wav',
  'woff',
  'woff2',
  'ttf',
  'otf',
  'eot',
  'so',
  'dll',
  'dylib',
  'class',
  'jar',
]);

const SNAPSHOT_EXTENSIONS = new Set(['snap']);

const GENERATED_HEADER_HINTS = [
  '@generated',
  'generated by',
  'do not edit',
  'this file is auto-generated',
  'autogenerated',
  'eslint-disable',
];

/** Threshold above which a single file's diff is considered "oversized" and summarized. */
const OVERSIZED_LINE_THRESHOLD = 1500;

function lower(s: string): string {
  return s.toLowerCase();
}

function basename(path: string): string {
  return path.split('/').pop() ?? path;
}

function extension(path: string): string {
  const base = basename(path);
  const dot = base.lastIndexOf('.');
  if (dot <= 0) return '';
  return base.slice(dot + 1).toLowerCase();
}

function countLines(file: DiffFile): { added: number; removed: number; total: number } {
  let added = 0;
  let removed = 0;
  for (const hunk of file.hunks) {
    for (const line of hunk.lines) {
      if (line.type === 'add') added++;
      else if (line.type === 'remove') removed++;
    }
  }
  return { added, removed, total: added + removed };
}

function looksGeneratedByContent(file: DiffFile): boolean {
  const SCAN_LIMIT = 6;
  let scanned = 0;
  for (const hunk of file.hunks) {
    for (const line of hunk.lines) {
      if (scanned >= SCAN_LIMIT) return false;
      const content = lower(line.content);
      if (GENERATED_HEADER_HINTS.some((hint) => content.includes(hint))) return true;
      scanned++;
    }
  }
  return false;
}

export function classifyFile(file: DiffFile): DroppedFile['reason'] | null {
  const reasonByPath = classifyPath(file.file);
  if (reasonByPath) return reasonByPath;
  if (looksGeneratedByContent(file)) return 'generated';
  return null;
}

/**
 * Path-only classification — used when we don't have the file contents in
 * hand (e.g. the test suite, or when something else only tracks paths).
 * Skips the @generated header check.
 */
export function classifyPath(path: string): DroppedFile['reason'] | null {
  const lowered = lower(path);
  const base = lower(basename(path));
  const ext = extension(path);

  if (BINARY_EXTENSIONS.has(ext)) return 'binary';
  if (LOCKFILE_BASENAMES.has(base)) return 'lockfile';
  if (SNAPSHOT_EXTENSIONS.has(ext)) return 'snapshot';
  if (SNAPSHOT_PATH_FRAGMENTS.some((frag) => lowered.includes(frag))) return 'snapshot';
  if (GENERATED_PATH_FRAGMENTS.some((frag) => lowered.includes(frag))) return 'generated';
  if (VENDORED_PATH_FRAGMENTS.some((frag) => lowered.includes(frag))) return 'vendored';
  if (base.endsWith('.min.js') || base.endsWith('.min.css')) return 'minified';
  if (ext === 'map' && (base.endsWith('.js.map') || base.endsWith('.css.map') || base.endsWith('.mjs.map')))
    return 'generated';
  return null;
}

/** Path-only "is this mechanical/noise" predicate. Compatible with the older API. */
export function isMechanicalFile(path: string): boolean {
  return classifyPath(path) !== null;
}

/**
 * Partition a list of diff files into ones worth narrating and ones to skip.
 * Path-based only (mirrors the older API that the prompt builder uses to
 * avoid shipping lockfiles/generated/vendored content to the LLM).
 */
export function partitionMechanicalFiles(files: DiffFile[]): { narrate: DiffFile[]; skipped: DiffFile[] } {
  const narrate: DiffFile[] = [];
  const skipped: DiffFile[] = [];
  for (const f of files) {
    if (isMechanicalFile(f.file)) skipped.push(f);
    else narrate.push(f);
  }
  return { narrate, skipped };
}

/**
 * Filter a diff to drop files that have no review value. Returns the kept
 * files plus a summary of what was dropped so the prompt can mention it.
 */
export function filterDiff(files: DiffFile[]): FilterResult {
  const kept: DiffFile[] = [];
  const dropped: DroppedFile[] = [];

  for (const file of files) {
    const reason = classifyFile(file);
    const counts = countLines(file);

    if (reason !== null) {
      dropped.push({ file: file.file, reason, added: counts.added, removed: counts.removed });
      continue;
    }

    if (counts.total > OVERSIZED_LINE_THRESHOLD) {
      // Oversized file — keep only the first hunk and a tail-summary so the
      // model still sees structure but doesn't drown in raw lines.
      const truncated: DiffFile = {
        ...file,
        hunks: file.hunks.slice(0, 1),
      };
      kept.push(truncated);
      const remainingHunks = file.hunks.length - 1;
      if (remainingHunks > 0) {
        dropped.push({
          file: `${file.file} (${remainingHunks} more hunk${remainingHunks === 1 ? '' : 's'})`,
          reason: 'oversized',
          added: counts.added,
          removed: counts.removed,
        });
      }
      continue;
    }

    kept.push(file);
  }

  return { kept, dropped };
}

export function summarizeDropped(dropped: DroppedFile[]): string {
  if (dropped.length === 0) return '';
  const lines = dropped.map((d) => `- ${d.file} (${d.reason}, +${d.added}/-${d.removed})`);
  return `Files omitted from the diff (no review value):\n${lines.join('\n')}`;
}
