import { describe, expect, it } from 'vitest';
import { classifyFile, filterDiff } from '../narrative/diff-filter';
import type { DiffFile } from '../github/types';

function makeFile(path: string, opts?: { addLines?: number; isNewFile?: boolean; bodyLines?: string[] }): DiffFile {
  const addLines = opts?.addLines ?? 3;
  const lines = (opts?.bodyLines ?? Array.from({ length: addLines }, (_, i) => `value-${i}`)).map((content, i) => ({
    type: 'add' as const,
    content,
    lineNumber: { new: i + 1 },
  }));
  return {
    file: path,
    isNewFile: opts?.isNewFile ?? false,
    isDeleted: false,
    hunks: [
      {
        header: '@@ -0,0 +1,3 @@',
        oldStart: 0,
        oldCount: 0,
        newStart: 1,
        newCount: lines.length,
        lines,
      },
    ],
  };
}

describe('classifyFile', () => {
  it('flags lockfiles by basename', () => {
    expect(classifyFile(makeFile('package-lock.json'))).toBe('lockfile');
    expect(classifyFile(makeFile('packages/web/bun.lock'))).toBe('lockfile');
  });

  it('flags binary files by extension', () => {
    expect(classifyFile(makeFile('docs/screenshot.png'))).toBe('binary');
    expect(classifyFile(makeFile('public/icon.ico'))).toBe('binary');
  });

  it('flags snapshot directories and .snap files', () => {
    expect(classifyFile(makeFile('src/__snapshots__/foo.snap.tsx'))).toBe('snapshot');
    expect(classifyFile(makeFile('src/foo.test.ts.snap'))).toBe('snapshot');
  });

  it('flags generated paths', () => {
    expect(classifyFile(makeFile('packages/web/dist/assets/index-abc.js'))).toBe('generated');
    expect(classifyFile(makeFile('src/__generated__/types.ts'))).toBe('generated');
  });

  it('flags vendored paths', () => {
    expect(classifyFile(makeFile('vendor/lib/foo.js'))).toBe('vendored');
    expect(classifyFile(makeFile('third_party/zlib.c'))).toBe('vendored');
  });

  it('flags @generated header in file content', () => {
    const f = makeFile('src/types.ts', { bodyLines: ['// @generated by codegen', 'export const x = 1;'] });
    expect(classifyFile(f)).toBe('generated');
  });

  it('keeps regular source files', () => {
    expect(classifyFile(makeFile('src/auth/middleware.ts'))).toBeNull();
    expect(classifyFile(makeFile('packages/cli/src/server.ts'))).toBeNull();
  });
});

describe('filterDiff', () => {
  it('drops noise files and keeps source files', () => {
    const files: DiffFile[] = [
      makeFile('src/index.ts'),
      makeFile('package-lock.json'),
      makeFile('packages/web/dist/assets/index.js'),
    ];
    const result = filterDiff(files);
    expect(result.kept).toHaveLength(1);
    expect(result.kept[0]?.file).toBe('src/index.ts');
    expect(result.dropped).toHaveLength(2);
    expect(result.dropped.map((d) => d.reason).sort()).toEqual(['generated', 'lockfile']);
  });

  it('truncates oversized diffs to first hunk and records the rest as dropped', () => {
    const huge: DiffFile = {
      file: 'src/big.ts',
      isNewFile: false,
      isDeleted: false,
      hunks: [
        {
          header: '@@ -1,1700 +1,1700 @@',
          oldStart: 1,
          oldCount: 1700,
          newStart: 1,
          newCount: 1700,
          lines: Array.from({ length: 1700 }, (_, i) => ({
            type: 'add' as const,
            content: `line ${i}`,
            lineNumber: { new: i + 1 },
          })),
        },
        {
          header: '@@ -2000,5 +2000,5 @@',
          oldStart: 2000,
          oldCount: 5,
          newStart: 2000,
          newCount: 5,
          lines: [],
        },
      ],
    };
    const result = filterDiff([huge]);
    expect(result.kept).toHaveLength(1);
    expect(result.kept[0]?.hunks).toHaveLength(1);
    expect(result.dropped.some((d) => d.reason === 'oversized')).toBe(true);
  });
});
